List<Map<String, String>> flashcards = [
  // Family Topic Flashcards
  {
    'word': 'Father',
    'video': 'father_video.mp4',
    'image': 'father_image.png',
    'braille': '⠋⠁⠓⠑⠗',
    'description': 'A male parent.',
  },
  {
    'word': 'Mother',
    'video': 'mother_video.mp4',
    'image': 'mother_image.png',
    'braille': '⠍⠕⠞⠑',
    'description': 'A female parent.',
  },
  {
    'word': 'Brother',
    'video': 'brother_video.mp4',
    'image': 'brother_image.png',
    'braille': '⠃⠗⠕⠎⠑⠗',
    'description': 'A male sibling.',
  },
  {
    'word': 'Sister',
    'video': 'sister_video.mp4',
    'image': 'sister_image.png',
    'braille': '⠎⠊⠎⠞',
    'description': 'A female sibling.',
  },
  {
    'word': 'Friend',
    'video': 'friend_video.mp4',
    'image': 'friend_image.png',
    'braille': '⠋⠗⠊⠑⠝⠙',
    'description': 'A person with whom one has a bond of mutual affection.',
  },
  {
    'word': 'Teacher',
    'video': 'teacher_video.mp4',
    'image': 'teacher_image.png',
    'braille': '⠞⠑⠁⠉⠓⠑',
    'description': 'A person who educates others.',
  },

  // Animal Topic Flashcards
  {
    'word': 'Lion',
    'video': 'lion_video.mp4',
    'image': 'lion_image.png',
    'braille': '⠇⠊⠕⠝',
    'description': 'A large carnivorous feline animal.',
  },
  {
    'word': 'Elephant',
    'video': 'elephant_video.mp4',
    'image': 'elephant_image.png',
    'braille': '⠑⠇⠑⠋⠁⠝⠞',
    'description': 'A large herbivorous mammal with a trunk.',
  },
  {
    'word': 'Tiger',
    'video': 'tiger_video.mp4',
    'image': 'tiger_image.png',
    'braille': '⠞⠊⠛⠑⠗',
    'description': 'A large striped carnivorous feline animal.',
  },
  {
    'word': 'Giraffe',
    'video': 'giraffe_video.mp4',
    'image': 'giraffe_image.png',
    'braille': '⠛⠊⠗⠁⠋⠑',
    'description': 'A tall mammal with a long neck.',
  },
  {
    'word': 'Zebra',
    'video': 'zebra_video.mp4',
    'image': 'zebra_image.png',
    'braille': '⠵⠑⠃⠗⠁',
    'description': 'A mammal with black-and-white striped fur.',
  },

  // School Topic Flashcards
  {
    'word': 'Teacher',
    'video': 'teacher_video.mp4',
    'image': 'teacher_image.png',
    'braille': '⠞⠑⠁⠉⠓⠑',
    'description': 'A person who educates others.',
  },
  {
    'word': 'Student',
    'video': 'student_video.mp4',
    'image': 'student_image.png',
    'braille': '⠎⠥⠞⠑⠝⠞',
    'description': 'A person who is learning at a school or college.',
  },
  {
    'word': 'Classroom',
    'video': 'classroom_video.mp4',
    'image': 'classroom_image.png',
    'braille': '⠉⠇⠁⠎⠎⠗⠕⠕⠍',
    'description': 'A room in which classes are held.',
  },
  {
    'word': 'Homework',
    'video': 'homework_video.mp4',
    'image': 'homework_image.png',
    'braille': '⠓⠕⠍⠑⠗⠅',
    'description':
        'Assignments given to students to complete outside of class.',
  },
  {
    'word': 'Notebook',
    'video': 'notebook_video.mp4',
    'image': 'notebook_image.png',
    'braille': '⠝⠕⠃⠑⠗⠅',
    'description': 'A book for writing notes in class.',
  },

  // Sport Topic Flashcards
  {
    'word': 'Football',
    'video': 'football_video.mp4',
    'image': 'football_image.png',
    'braille': '⠋⠕⠕⠞⠊⠇⠇',
    'description':
        'A game played between two teams of eleven players with a round ball.',
  },
  {
    'word': 'Basketball',
    'video': 'basketball_video.mp4',
    'image': 'basketball_image.png',
    'braille': '⠃⠁⠎⠅⠑⠞⠃⠁⠇⠇',
    'description':
        'A game played between two teams of five players with a round ball.',
  },
  {
    'word': 'Tennis',
    'video': 'tennis_video.mp4',
    'image': 'tennis_image.png',
    'braille': '⠞⠑⠝⠝⠊⠎',
    'description': 'A sport played with rackets and a ball on a court.',
  },
  {
    'word': 'Swimming',
    'video': 'swimming_video.mp4',
    'image': 'swimming_image.png',
    'braille': '⠎⠺⠊⠍⠍⠊⠝⠛',
    'description': 'The sport or activity of moving through water.',
  },
  {
    'word': 'Running',
    'video': 'running_video.mp4',
    'image': 'running_image.png',
    'braille': '⠗⠥⠝⠝⠊⠝⠛',
    'description': 'The act of moving rapidly on foot.',
  },

  // Physics Topic Flashcards
  {
    'word': 'Force',
    'video': 'force_video.mp4',
    'image': 'force_image.png',
    'braille': '⠋⠕⠗⠉⠑',
    'description':
        'A push or pull on an object resulting from its interaction with another object.',
  },
  {
    'word': 'Energy',
    'video': 'energy_video.mp4',
    'image': 'energy_image.png',
    'braille': '⠑⠝⠑⠗⠛⠽',
    'description': 'The capacity to do work or cause change.',
  },
  {
    'word': 'Mass',
    'video': 'mass_video.mp4',
    'image': 'mass_image.png',
    'braille': '⠍⠁⠎⠎',
    'description': 'A measure of the amount of matter in an object.',
  },
  {
    'word': 'Velocity',
    'video': 'velocity_video.mp4',
    'image': 'velocity_image.png',
    'braille': '⠧⠑⠇⠕⠉⠊⠑',
    'description': 'The speed of something in a given direction.',
  },
  {
    'word': 'Acceleration',
    'video': 'acceleration_video.mp4',
    'image': 'acceleration_image.png',
    'braille': '⠁⠉⠉⠑⠇⠑⠗⠁⠞⠊⠕⠝',
    'description': 'The rate at which an object changes its velocity.',
  },

  // Additional Flashcards
  {
    'word': 'Grandmother',
    'video': 'grandmother_video.mp4',
    'image': 'grandmother_image.png',
    'braille': '⠛⠗⠁⠝⠙⠍⠕⠞⠓⠑⠗',
    'description': 'The mother of one’s parent.',
  },
  {
    'word': 'Grandfather',
    'video': 'grandfather_video.mp4',
    'image': 'grandfather_image.png',
    'braille': '⠛⠗⠁⠝⠙⠋⠁⠞⠓⠑⠗',
    'description': 'The father of one’s parent.',
  },
  {
    'word': 'Chalkboard',
    'video': 'chalkboard_video.mp4',
    'image': 'chalkboard_image.png',
    'braille': '⠉⠓⠁⠇⠅⠃⠕⠁⠗⠙',
    'description': 'A board for writing on with chalk.',
  },
  {
    'word': 'Monkey',
    'video': 'monkey_video.mp4',
    'image': 'monkey_image.png',
    'braille': '⠍⠕⠝⠅⠑⠽',
    'description': 'A small to medium-sized primate.',
  },
  {
    'word': 'Cycling',
    'video': 'cycling_video.mp4',
    'image': 'cycling_image.png',
    'braille': '⠉⠽⠉⠇⠊⠝⠛',
    'description': 'The sport or activity of riding a bicycle.',
  },
  {
    'word': 'Momentum',
    'video': 'momentum_video.mp4',
    'image': 'momentum_image.png',
    'braille': '⠍⠕⠍⠑⠝⠞⠥⠍',
    'description': 'The product of an object’s mass and velocity.',
  },
  {
    'word': 'Engineer',
    'video': 'engineer_video.mp4',
    'image': 'engineer_image.png',
    'braille': '⠑⠝⠛⠊⠝⠑⠑⠗',
    'description': 'A person who designs and builds complex systems.',
  },
  {
    'word': 'Doctor',
    'video': 'doctor_video.mp4',
    'image': 'doctor_image.png',
    'braille': '⠙⠕⠉⠞⠕⠗',
    'description': 'A person qualified to treat the sick.',
  },
  {
    'word': 'Lawyer',
    'video': 'lawyer_video.mp4',
    'image': 'lawyer_image.png',
    'braille': '⠇⠁⠺⠽⠑⠗',
    'description': 'A person who practices or studies law.',
  },
  {
    'word': 'Architect',
    'video': 'architect_video.mp4',
    'image': 'architect_image.png',
    'braille': '⠁⠗⠉⠓⠊⠞⠑⠉⠞',
    'description': 'A person who designs buildings.',
  },
  {
    'word': 'Scientist',
    'video': 'scientist_video.mp4',
    'image': 'scientist_image.png',
    'braille': '⠎⠉⠊⠑⠝⠞⠊⠎⠞',
    'description': 'A person who studies the natural world.',
  },
];
